### ISSUE TITLE
Exception when using Bard Bloodletter feature

### ISSUE THREAD

**Issue by senyszrm** [daemitus/XIVComboPlugin#165]
This is the error I get in my dalamud.log file when I try to use this feature:

```
System.InvalidOperationException: Function pointer for ActionManager::GetRecastGroupDetail is null. Did you forget to call Resolver.Initialize?
   at FFXIVClientStructs.FFXIV.Client.Game.ActionManager.GetRecastGroupDetail(Int32 recastGroup) in ᚸꩁń:line 182
   at XIVComboExpandedPlugin.CustomComboCache.GetCooldown(UInt32 actionID)
   at XIVComboExpandedPlugin.Combos.CustomCombo.<CalcBestAction>g__Selector|11_1(UInt32 actionID)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at XIVComboExpandedPlugin.Combos.CustomCombo.CalcBestAction(UInt32 original, UInt32[] actions)
   at XIVComboExpandedPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID)
   at XIVComboExpandedPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID)
```

**Comment by daemitus** [comment]
What version of dalamud and combo are you running.

**Comment by senyszrm** [comment]
Hmm, seems like something was going wrong with my local environment. I was using a checked out version of master and pulled since the new api/dalamud. After cleaning everything and rebuilding it's working. Sorry.
